# Generated by Django 5.0.7 on 2024-07-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_authors_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='book',
            field=models.ManyToManyField(to='book.book'),
        ),
    ]
