# Generated by Django 5.0.7 on 2024-07-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_collection_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorsModel',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='tittle',
            new_name='name',
        ),
    ]
